services:
  - type: web
    name: django-portfolio
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn example.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: example.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: your-django-secret-key
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: django-portfolio-bulelani.onrender.com
